# Generated by Django 3.2.25 on 2026-06-23 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('release_year', models.IntegerField()),
                ('lyrics', models.TextField()),
                ('is_single', models.BooleanField(default=True)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=0)),
                ('votes', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-rating', '-total_votes'],
            },
        ),
    ]
